# Generated by Django 3.2.5 on 2021-07-14 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_commented_on',
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='commenter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.commenter'),
        ),
    ]
