# Generated by Django 3.2.5 on 2021-07-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenter',
            name='commenter_username',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
