# Generated by Django 3.2.5 on 2021-07-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
